package com.nulll.jar.civ.common.core;

import java.io.File;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Arrays;

import sun.misc.Unsafe;
import sun.reflect.FieldAccessor;
import sun.reflect.ReflectionFactory;
import net.minecraft.network.ServerStatusResponse;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.ModContainer;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartedEvent;

import com.nulll.jar.civ.common.proxy.ICivProxy;
import com.nulll.jar.civ.common.util.ModUtils;
import com.nulll.jar.civ.common.util.java.Reflect;
import com.nulll.jar.civ.common.util.java.ZipUtil;
import com.sun.istack.internal.Nullable;

@Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.MOD_VERSION)
public class MineCiv
{

	@SidedProxy(clientSide = Constants.CLIENT_PROXY, serverSide = Constants.SERVER_PROXY)
	public static ICivProxy PROXY;

	@Mod.Metadata
	public static ModMetadata METADATA;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) throws Exception
	{

		setupMetadata();

		PROXY.preInit(event);
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		PROXY.init(event);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		PROXY.postInit(event);
	}

	@EventHandler
	public void onStarted(FMLServerStartedEvent event)
	{

	}

	private void setupMetadata()
	{
		ModUtils.setDisableablility(Loader.instance().activeModContainer(), ModContainer.Disableable.NEVER);

		METADATA.autogenerated = false;
		METADATA.modId = Constants.MOD_ID;
		METADATA.name = Constants.MOD_NAME;
		METADATA.version = Constants.MOD_VERSION;
		METADATA.description = Constants.MOD_DESC;
		METADATA.authorList = Constants.MOD_AUTHORS;
		METADATA.credits = Constants.MOD_CREDITS;
		METADATA.logoFile = Constants.MOD_LOGO;
		METADATA.url = Constants.MOD_URL;
	}

}
